nxp-imx6: upgrade the wayland-protocols & gstreamer1.0
Issue: LIN1023-5317

Since the meta-imx & meta-freescale layers have upgraded to the
new version, the package specific version specified by bsp requires
corresponding upgrades.

And add 'pugixml' to resolve below issue:

ERROR: Nothing PROVIDES 'pugixml' (but meta-imx/meta-sdk/recipes-graphics/imx-gpu-sdk/imx-gpu-sdk_6.2.1.bb DEPENDS on or otherwise requires it)
pugixml was skipped: You are about to enable third-party components, there is additional third-part licensing involved, and you might need to
consult with your legal department. pugixml was skipped: Not supported in this configuration by Wind River. To override, add to your local.conf:
CUSTOMER_RECIPES:openembedded-layer += 'pugixml'

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>