nxp-imx6: Move override 'mx6-nxp-bsp' to gpu hardware feature exclusive
Issue: LIN1023-5364 LIN1023-5371

Move the override 'mx6-nxp-bsp' to the README of GPU chapter such as:
MACHINEOVERRIDES:prepend:nxp-imx6 = "......mx6sx-nxp-bsp:mx6-nxp-bsp:"

To avoid below building issue when building wrlinux-graphics without
hardware graphic feature enabled.

ERROR: Nothing PROVIDES 'virtual/libg2d' (but oe-core/meta/recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.22.6.bb DEPENDS on or otherwise requires it)
imx-pxp-g2d PROVIDES virtual/libg2d but was skipped: incompatible with machine nxp-imx6 (not in COMPATIBLE_MACHINE)

Since PACKAGECONFIG_GL:append:mx6-nxp-bsp = "viv-fb", and
PACKAGECONFIG[viv-fb] = ",,virtual/libgles2 virtual/libg2d", this will
require 'libg2d' which is provided by 'imx-gpu-g2d' and it's gpu hardware
feature exclusive.

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>